### ISSUE TITLE
Just two questions

### ISSUE THREAD

**Issue by Mizobrook-kan** [cmuparlay/parlaylib#12]
1. Why is [`num_deques`](https://github.com/cmuparlay/parlaylib/blob/master/include/parlay/scheduler.h#L138) two times as great as `nums_thread`?
2. Could you provide details about [Coupon collector's problem](https://github.com/cmuparlay/parlaylib/blob/master/include/parlay/scheduler.h#L256) in this context?

**Comment by shwestrick** [comment]
The [Coupon collector's problem](https://en.wikipedia.org/wiki/Coupon_collector%27s_problem) says that you need approximately `nlog(n)` samples before you will have touched every element at least once. This holds [whp](https://en.wikipedia.org/wiki/With_high_probability). So for `n` deques, if a processor does `nlog(n)` steal attempts, then it is very likely that the processor will have inspected every deque at least once. The implementation here hardcodes `100n` because in practice `log(n)` is much smaller than `100`.

I don't remember why the scheduler sets `num_deques = 2 * num_threads`... and I don't see in the code where the extra deques are used. Perhaps @gblelloch can comment?

**Comment by Mizobrook-kan** [comment]
Your comment on coupon collector's problem makes sense. Thank you.
