### ISSUE TITLE
Unexpected behavior of parlay::any_of

### ISSUE THREAD

**Issue by xindubawukong** [cmuparlay/parlaylib#60]
![image](https://github.com/cmuparlay/parlaylib/assets/22728970/08666d8c-b225-4f14-89c6-398954e5381c)

Shouldn't it be `count_if(...) > 0`?

Code link: https://github.com/cmuparlay/parlaylib/blob/master/include/parlay/primitives.h#L572-L577

**Comment by DanielLiamAnderson** [comment]
Yep (or it probably meant to say `>= 1`).  I guess no one has ever used this function before.

**Comment by xindubawukong** [comment]
haha, I just run in to this issue when I have a sequence with only one true value.

**Comment by DanielLiamAnderson** [comment]
![image](https://github.com/cmuparlay/parlaylib/assets/20237923/fd6b6c65-51ae-4618-8bee-beddc3168ac9)

Yeah I just looked back at PbbsLib, the predecessor of ParlayLib where this function was inherited from, and the bug is there too.  So literally no one has noticed for five years lol.  So thanks for finding it haha.  Good thing its an easy fix.

**Comment by xindubawukong** [comment]
Hi @DanielLiamAnderson do you have time to fix this issue?

**Comment by DanielLiamAnderson** [comment]
Fixed now!
